services:
  # Main application
  - type: web
    name: chat-xray-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: PORT
        value: 8000
      - key: USE_LOCAL_LLM
        value: "false"
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: WEBHOOK_PATH
        value: /webhook
      - key: UPLOAD_RETENTION_HOURS
        value: 1
      - key: REPORT_RETENTION_HOURS
        value: 72
      - key: ENABLE_COST_TRACKING
        value: true
    healthCheckPath: /health 