import pytest
import os
from weasyprint import HTML
from app.services.local_llm import LocalLLM
from app.services.render import render_pdf

def test_weasyprint_installation():
    """Test that WeasyPrint is properly installed and can create a PDF"""
    html_content = """
    <html>
        <body>
            <h1>Test PDF</h1>
            <p>This is a test PDF generated by WeasyPrint</p>
        </body>
    </html>
    """
    pdf_path = "test_output.pdf"
    try:
        # Test direct WeasyPrint usage
        HTML(string=html_content).write_pdf(pdf_path)
        assert os.path.exists(pdf_path)
        
        # Test our render service
        render_pdf(html_content, pdf_path)
        assert os.path.exists(pdf_path)
    finally:
        if os.path.exists(pdf_path):
            os.remove(pdf_path)

def test_ollama_connection():
    """Test that we can connect to Ollama service"""
    llm = LocalLLM()
    
    # Test connection
    assert llm.is_available(), "Ollama service is not available"
    
    # Test simple completion
    response = llm.generate("Say hello")
    assert response is not None
    assert isinstance(response, str)
    assert len(response) > 0

@pytest.mark.asyncio
async def test_ollama_async():
    """Test async Ollama functionality"""
    llm = LocalLLM()
    
    # Test async completion
    response = await llm.generate_async("Say hello")
    assert response is not None
    assert isinstance(response, str)
    assert len(response) > 0 